# Manual Exercise

In [1]:
import numpy as np

# 2.

In [62]:
data1 = np.array([1,3,9,12,18])

data2 = np.array(
    [[1,5,2,0],
    [3,6,4,7]])

data3 = np.array([
    [7,6],
    [5,4],
    [3,2]])

data4 = np.array([
    [11,52,20,50],
    [34,61,43,17]])

# 3.

In [37]:
data1 = data1 + data1
data1 = data1 * 10

data1 = data1.astype(int)
data2 = data2.astype(int)
data3 = data3.astype(int)
data4 = data4.astype(int)

data1

array([ 20,  60, 180, 240, 360])

# 4.

In [38]:
arr1 = np.zeros((3,5))

arr2 = np.ones((2,8))

arr3 = np.random.randint(0,10,size=(6,3))

# 5.

In [47]:
data1[2:4] = data1[2:4]**2

data2[0,1] = data2[0,1]**2
data2[1,2] = data2[1,2]**2
data2

array([[ 1, 25,  2,  0],
       [ 3,  6, 16,  7]])

# 6.

In [50]:
array = np.array([
    ['ML', 'OS', 'CCN'],
    ['OS', 'AI', 'MP'],
    ['CCN', 'ML', 'AI']])

array[(array != 'ML') & (array != 'AI')] = 0

# 7.

In [53]:
data2 = data2.T
data3 = data3.T
data4 = data4.T

# 8.

In [56]:
np.hstack((data2,data4))

array([[ 1,  5,  2,  0, 11, 52, 20, 50],
       [ 3,  6,  4,  7, 34, 61, 43, 17]])

In [58]:
np.vstack((data2,data4))

array([[ 1,  5,  2,  0],
       [ 3,  6,  4,  7],
       [11, 52, 20, 50],
       [34, 61, 43, 17]])

# 9.

In [61]:
means = data2.mean(axis=0)

data2 = data2 - means

data2

array([[-1. , -0.5, -1. , -3.5],
       [ 1. ,  0.5,  1. ,  3.5]])

# 10.

In [63]:
data2 = data2.reshape(4,2)
data2

array([[1, 5],
       [2, 0],
       [3, 6],
       [4, 7]])

# 11.

In [66]:
marks = np.array([[60,70,50],
                  [40,60,80],
                  [70,55,65]])

marks.max(axis=1)

array([70, 80, 70])

# 12.

In [ ]:
cgpa = 

# 13.

# 14.

In [72]:
matrix = np.random.randint(1,10,size=(4,4))
dotprod = np.dot(matrix, matrix)
inverse = np.linalg.inv(matrix)

# 15.

In [73]:
np.save('data1.npy', data1)
np.save('data2.npy', data2)
np.save('data3.npy', data3)
np.save('data4.npy', data4)